name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: ["*"]
  push:
    branches: ["master"]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    services:
      eventstore:
        image: eventstore/eventstore:latest
        env:
          EVENTSTORE_CLUSTER_SIZE: 1
          EVENTSTORE_RUN_PROJECTIONS: All
          EVENTSTORE_START_STANDARD_PROJECTIONS: true
          EVENTSTORE_HTTP_PORT: 2113
          EVENTSTORE_INSECURE: true
        ports: ["2113:2113"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # this is important! otherwise the restoring of the mtime won't work properly
          fetch-depth: 0

      - name: Restore timestamps
        uses: ./.github/actions/restore-mtime

      - name: Install Elixir
        uses: ./.github/actions/asdf

      - name: Elixir cache
        uses: ./.github/actions/elixir-cache

      - name: Mix dependencies
        run: mix deps.get

      - name: Checks
        run: mix check
